### ISSUE TITLE
Cannot get out of "replace"

### ISSUE THREAD

**Issue by 3b1b** [kevinbarabash/mobile-keypad#46]
If you change your mind after clicking "replace" the only way to escape is with an undo.

**Comment by k4b7** [comment]
yes, this really painful

**Comment by k4b7** [comment]
fixed in https://github.com/Khan/algebra-tool/commit/42354a4956098d2f3179887ca8118940d11974b7

**Comment by k4b7** [comment]
![screen shot 2016-03-05 at 8 51 47 pm](https://cloud.githubusercontent.com/assets/1044413/13552358/19a8168a-e314-11e5-88b5-a3ff0e25518d.png)

Hitting the `x` takes you back to the content menu for the current selection.
