### ISSUE TITLE
No way to simplify 1/(1/x)

### ISSUE THREAD

**Issue by 3b1b** [kevinbarabash/mobile-keypad#47]

**Comment by k4b7** [comment]
I think for this one we probably want some sort of transform that changes `1/(1/x)` to `1*(x/1)` and more generally `(a/b)/(c/d)` to `(a/b)*(d/c)`.  In the case of `1*(x/1)` division by `1` and multiplication by `1` could automatically be removed.

**Comment by k4b7** [comment]
Another feature I want to add is be able to multiple the current selection or expression by something an expression equivalent to `1`.  In this situation you'd then be able to multiple `1/(1/x)` by `x/x` and then reduce the denominator to `1`.

**Comment by k4b7** [comment]
fixed by https://github.com/Khan/algebra-tool/commit/30d14a9f4d0ef2376cdab07e750b8f65bd9567ae.
