### ISSUE TITLE
Add instructions to Readme

### ISSUE THREAD

**Issue by soegaard** [kevinbarabash/mobile-keypad#52]
A note on what to do after cloning the repo is needed.
How to build and how to start a local server.

**Comment by k4b7** [comment]
To get started you'll need to run:

```
npm install
npm start
node api-server.js // in a separate terminal
```

Then open `localhost:3000` in your browser.

I'll add the instructions to the readme too.

**Comment by soegaard** [comment]
Should I use a specific node version?
I get this:

mbp:algebra-tool soegaard$ node api-server.js
/Users/soegaard/Dropbox/GitHub/algebra-tool/api-server.js:15
server.post('/api/steps', (req, res, next) => {
                                           ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

mbp:algebra-tool soegaard$ node --version
v0.12.5

2016-03-18 16:22 GMT+01:00 Kevin Barabash notifications@github.com:

> To get started you'll need to run:
> 
> npm install
> npm start
> node api-server.js // in a separate terminal
> 
> Then open localhost:3000 in your browser.
> 
> I'll add the instructions to the readme too.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Khan/algebra-tool/issues/52#issuecomment-198407491

## 

## 

Jens Axel Søgaard

**Comment by k4b7** [comment]
I think node 4+ should work.  It's because of the arrow functions in the code.  I should figure out how to specify which version of node works in the `package.json`.

**Comment by k4b7** [comment]
I've updated the README.

**Comment by soegaard** [comment]
Is there a step missing?

The file index.html refers to build/index.js but there is no build
directory.

2016-03-19 6:40 GMT+01:00 Kevin Barabash notifications@github.com:

> I've updated the README.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Khan/algebra-tool/issues/52#issuecomment-198639790

## 

## 

Jens Axel Søgaard

**Comment by soegaard** [comment]
I figured out I need to install webpack, webpack-dev-server, babel,
babel-core and restify using npm
before  running "npm install".

Now I get this error which explains, why I am missing build/index.js.

ERROR in ./src/index.js
Module build failed: Error: Couldn't find preset "stage-1" relative to
directory "/Users/soegaard/Dropbox/GitHub/algebra-tool"
    at
/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.addConfig
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/index.js:123:22)

2016-03-19 9:36 GMT+01:00 Jens Axel Søgaard jensaxel@soegaard.net:

> Is there a step missing?
> 
> The file index.html refers to build/index.js but there is no build
> directory.
> 
> 2016-03-19 6:40 GMT+01:00 Kevin Barabash notifications@github.com:
> 
> > I've updated the README.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/Khan/algebra-tool/issues/52#issuecomment-198639790
> 
> ## 
> 
> ## 
> 
> Jens Axel Søgaard

## 

## 

Jens Axel Søgaard

**Comment by k4b7** [comment]
> I figured out I need to install webpack, webpack-dev-server, babel,
> babel-core and restify using npm
> before  running "npm install".

`npm install` should be install those dependencies for you.  It sounds like you're missing `babel-preset-stage-1`.  In package.json, `babel-preset-stage-0` is listed as a dependencies.  `babel-preset-stage-1` is a dependency of `babel-preset-stage-0` so `npm install` should grab both of those.  Where are you running `npm install` from?

**Comment by soegaard** [comment]
Below is a transcript. Cloning a new repo and then running npm install.

I notice the three lines:

npm WARN peerDependencies The peer dependency babel-core@^6.0.0 included
from babel-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.

mbp:algebra-tool soegaard$ node --version
v4.4.0

mbp:algebra-tool soegaard$ npm --version
2.14.20

mbp:Downloads soegaard$ git clone https://github.com/Khan/algebra-tool.git
Cloning into 'algebra-tool'...
remote: Counting objects: 1647, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1647 (delta 0), reused 0 (delta 0), pack-reused 1644
Receiving objects: 100% (1647/1647), 433.92 KiB | 269.00 KiB/s, done.
Resolving deltas: 100% (1242/1242), done.
Checking connectivity... done.
mbp:Downloads soegaard$ cd algebra-tool/
mbp:algebra-tool soegaard$ ls
LICENSE api-server.js ka_leaf.png package.json server.js
webpack.config.dev.js
README.md index.html metrics screenshot.png src webpack.prod.config.js

mbp:algebra-tool soegaard$ npm install
npm WARN peerDependencies The peer dependency babel-core@^6.0.0 included
from babel-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
|

> dtrace-provider@0.6.0 install
> /Users/soegaard/Downloads/algebra-tool/node_modules/restify/node_modules/dtrace-provider
> node scripts/install.js

/

> fsevents@1.0.8 install
> /Users/soegaard/Downloads/algebra-tool/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success:
"/Users/soegaard/Downloads/algebra-tool/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node"
is installed via remote
json-loader@0.5.4 node_modules/json-loader

react-dom@0.14.7 node_modules/react-dom

functify@0.4.0 node_modules/functify

webpack-dev-server@1.14.1 node_modules/webpack-dev-server
├── connect-history-api-fallback@1.1.0
├── stream-cache@0.0.2
├── strip-ansi@3.0.1 (ansi-regex@2.0.0)
├── supports-color@3.1.2 (has-flag@1.0.0)
├── http-proxy@1.13.2 (eventemitter3@1.2.0, requires-port@1.0.0)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── compression@1.6.1 (on-headers@1.0.1, bytes@2.2.0, vary@1.1.0,
compressible@2.0.7, debug@2.2.0, accepts@1.3.2)
├── express@4.13.4 (escape-html@1.0.3, array-flatten@1.1.1,
utils-merge@1.0.0, cookie-signature@1.0.6, vary@1.0.1, content-type@1.0.1,
methods@1.1.2, merge-descriptors@1.0.1, content-disposition@0.5.1,
fresh@0.3.0, range-parser@1.0.3, path-to-regexp@0.1.7, serve-static@1.10.2,
parseurl@1.3.1, etag@1.7.0, cookie@0.1.5, depd@1.1.0, qs@4.0.0,
on-finished@2.3.0, finalhandler@0.4.1, debug@2.2.0, proxy-addr@1.0.10,
accepts@1.2.13, type-is@1.6.12, send@0.13.1)
├── webpack-dev-middleware@1.5.1 (mime@1.3.4, memory-fs@0.3.0)
├── sockjs@0.3.15 (node-uuid@1.4.7, faye-websocket@0.9.4)
├── serve-index@1.7.3 (escape-html@1.0.3, parseurl@1.3.1, batch@0.5.3,
http-errors@1.3.1, mime-types@2.1.10, debug@2.2.0, accepts@1.2.13)
└── sockjs-client@1.0.3 (json3@3.3.2, inherits@2.0.1, debug@2.2.0,
url-parse@1.0.5, eventsource@0.1.6, faye-websocket@0.7.3)

restify@4.0.4 node_modules/restify
├── assert-plus@0.1.5
├── tunnel-agent@0.4.2
├── escape-regexp-component@1.0.2
├── keep-alive-agent@0.0.1
├── negotiator@0.5.3
├── mime@1.3.4
├── lru-cache@2.7.3
├── formidable@1.0.17
├── node-uuid@1.4.7
├── qs@3.1.0
├── once@1.3.3 (wrappy@1.0.1)
├── semver@4.3.6
├── spdy@1.32.5
├── backoff@2.5.0 (precond@0.2.3)
├── http-signature@0.11.0 (ctype@0.5.3, asn1@0.1.11)
├── verror@1.6.1 (core-util-is@1.0.2, extsprintf@1.2.0)
├── csv@0.4.6 (csv-generate@0.0.6, csv-stringify@0.0.8,
stream-transform@0.1.1, csv-parse@1.0.2)
├── vasync@1.6.3 (verror@1.6.0)
├── dtrace-provider@0.6.0 (nan@2.2.0)
└── bunyan@1.8.0 (safe-json-stringify@1.0.3, mv@2.1.1, moment@2.12.0)

react-redux@4.4.1 node_modules/react-redux
├── invariant@2.2.1
├── hoist-non-react-statics@1.0.5
├── loose-envify@1.1.0 (js-tokens@1.0.2)
└── lodash@4.6.1

redux@3.3.1 node_modules/redux
├── loose-envify@1.1.0 (js-tokens@1.0.2)
├── lodash-es@4.6.1
└── lodash@4.6.1

babel-preset-react-hmre@1.1.1 node_modules/babel-preset-react-hmre
├── react-transform-catch-errors@1.0.2
├── redbox-react@1.2.2 (object-assign@4.0.1, error-stack-parser@1.3.3)
├── react-transform-hmr@1.0.4 (global@4.3.0, react-proxy@1.1.8)
└── babel-plugin-react-transform@2.0.2 (lodash@4.6.1)

babel-preset-react@6.5.0 node_modules/babel-preset-react
├── babel-plugin-syntax-jsx@6.5.0 (babel-runtime@5.8.35)
├── babel-plugin-syntax-flow@6.5.0 (babel-runtime@5.8.35)
├── babel-plugin-transform-flow-strip-types@6.7.0 (babel-runtime@5.8.35)
├── babel-plugin-transform-react-display-name@6.5.0 (babel-runtime@5.8.35)
├── babel-plugin-transform-react-jsx-source@6.5.0 (babel-runtime@5.8.35)
└── babel-plugin-transform-react-jsx@6.6.5
(babel-helper-builder-react-jsx@6.6.5, babel-runtime@5.8.35)

babel-preset-stage-0@6.5.0 node_modules/babel-preset-stage-0
├── babel-plugin-transform-function-bind@6.5.2
(babel-plugin-syntax-function-bind@6.5.0, babel-runtime@5.8.35)
├── babel-plugin-transform-do-expressions@6.5.0
(babel-plugin-syntax-do-expressions@6.5.0, babel-runtime@5.8.35)
└── babel-preset-stage-1@6.5.0
(babel-plugin-transform-class-constructor-call@6.6.5,
babel-plugin-transform-export-extensions@6.5.0,
babel-plugin-transform-class-properties@6.6.0,
babel-plugin-transform-decorators@6.6.5, babel-preset-stage-2@6.5.0)

react@0.14.7 node_modules/react
├── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
└── fbjs@0.6.1 (whatwg-fetch@0.9.0, ua-parser-js@0.7.10, loose-envify@1.1.0,
promise@7.1.1, core-js@1.2.6)

babel-polyfill@6.7.2 node_modules/babel-polyfill
├── babel-regenerator-runtime@6.5.0
├── babel-runtime@5.8.35 (core-js@1.2.6)
└── core-js@2.2.1

babel-preset-es2015@6.6.0 node_modules/babel-preset-es2015
├── babel-plugin-transform-es2015-block-scoped-functions@6.6.5
(babel-runtime@5.8.35)
├── babel-plugin-check-es2015-constants@6.7.2 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-typeof-symbol@6.6.0 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-destructuring@6.6.5 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-for-of@6.6.0 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-arrow-functions@6.5.2
(babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-spread@6.6.5 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-template-literals@6.6.5
(babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-literals@6.5.0 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-object-super@6.6.5
(babel-helper-replace-supers@6.7.0, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-modules-commonjs@6.7.0
(babel-plugin-transform-strict-mode@6.6.5, babel-template@6.7.0,
babel-types@6.7.2, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-computed-properties@6.6.5
(babel-helper-define-map@6.6.5, babel-template@6.7.0, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-unicode-regex@6.5.0 (regexpu-core@1.0.0,
babel-helper-regex@6.6.5, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-function-name@6.5.0 (babel-types@6.7.2,
babel-helper-function-name@6.6.0, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-block-scoping@6.7.1 (babel-template@6.7.0,
babel-types@6.7.2, babel-traverse@6.7.3, lodash@3.10.1, babel-runtime@5.8.35
)
├── babel-plugin-transform-es2015-duplicate-keys@6.6.4 (babel-types@6.7.2,
babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-sticky-regex@6.5.0
(babel-helper-regex@6.6.5, babel-types@6.7.2, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-shorthand-properties@6.5.0
(babel-types@6.7.2, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-classes@6.6.5
(babel-helper-replace-supers@6.7.0, babel-messages@6.7.2,
babel-helper-optimise-call-expression@6.6.0,
babel-helper-function-name@6.6.0, babel-helper-define-map@6.6.5,
babel-template@6.7.0, babel-types@6.7.2, babel-traverse@6.7.3,
babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-parameters@6.7.0
(babel-helper-get-function-arity@6.6.5, babel-helper-call-delegate@6.6.5,
babel-template@6.7.0, babel-types@6.7.2, babel-traverse@6.7.3,
babel-runtime@5.8.35)
└── babel-plugin-transform-regenerator@6.6.5
(babel-plugin-syntax-async-functions@6.5.0, private@0.1.6, babylon@6.7.0,
babel-types@6.7.2, babel-traverse@6.7.3, babel-runtime@5.8.35,
babel-core@6.7.2)

babel-core@6.7.2 node_modules/babel-core
├── slash@1.0.0
├── babel-messages@6.7.2
├── path-exists@1.0.0
├── shebang-regex@1.0.0
├── path-is-absolute@1.0.0
├── babel-template@6.7.0
├── babel-helpers@6.6.0
├── private@0.1.6
├── babylon@6.7.0
├── convert-source-map@1.2.0
├── source-map@0.5.3
├── debug@2.2.0 (ms@0.7.1)
├── babel-types@6.7.2 (to-fast-properties@1.0.1, esutils@2.0.2)
├── minimatch@2.0.10 (brace-expansion@1.1.3)
├── babel-code-frame@6.7.2 (js-tokens@1.0.2, esutils@2.0.2,
line-numbers@0.2.0, repeating@1.1.3, chalk@1.1.1)
├── babel-generator@6.7.2 (trim-right@1.0.1, repeating@1.1.3,
is-integer@1.0.6, detect-indent@3.0.1)
├── babel-traverse@6.7.3 (globals@8.18.0, repeating@1.1.3, invariant@2.2.1)
├── json5@0.4.0
├── lodash@3.10.1
├── babel-runtime@5.8.35 (core-js@1.2.6)
└── babel-register@6.7.2 (home-or-tmp@1.0.0, mkdirp@0.5.1,
source-map-support@0.2.10, core-js@2.2.1)

babel-loader@6.2.4 node_modules/babel-loader
├── object-assign@4.0.1
├── mkdirp@0.5.1 (minimist@0.0.8)
└── loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)

webpack@1.12.14 node_modules/webpack
├── interpret@0.6.6
├── tapable@0.1.10
├── clone@1.0.2
├── async@1.5.2
├── esprima@2.7.2
├── supports-color@3.1.2 (has-flag@1.0.0)
├── enhanced-resolve@0.9.1 (graceful-fs@4.1.3, memory-fs@0.2.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── memory-fs@0.3.0 (errno@0.1.4, readable-stream@2.0.6)
├── webpack-core@0.6.8 (source-map@0.4.4, source-list-map@0.1.5)
├── uglify-js@2.6.2 (async@0.2.10, uglify-to-browserify@1.0.2,
source-map@0.5.3, yargs@3.10.0)
├── loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)
├── node-libs-browser@0.5.3 (https-browserify@0.0.0, tty-browserify@0.0.0,
path-browserify@0.0.0, constants-browserify@0.0.1, punycode@1.4.0,
string_decoder@0.10.31, os-browserify@0.1.2, process@0.11.2, assert@1.3.0,
domain-browser@1.1.7, querystring-es3@0.2.1, timers-browserify@1.4.2,
events@1.1.0, stream-browserify@1.0.0, vm-browserify@0.0.4, util@0.10.3,
console-browserify@1.1.0, readable-stream@1.1.13, url@0.10.3,
http-browserify@1.7.0, buffer@3.6.0, browserify-zlib@0.1.4,
crypto-browserify@3.2.8)
└── watchpack@0.2.9 (graceful-fs@4.1.3, async@0.9.2, chokidar@1.4.3)

2016-03-19 16:58 GMT+01:00 Kevin Barabash notifications@github.com:

> I figured out I need to install webpack, webpack-dev-server, babel,
> babel-core and restify using npm
> before running "npm install".
> 
> npm install should be install those dependencies for you. It sounds like
> you're missing babel-preset-stage-1. In package.json, babel-preset-stage-0
> is listed as a dependencies. babel-preset-stage-1 is a dependency of
> babel-preset-stage-0 so npm install should grab both of those. Where are
> you running npm install from?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Khan/algebra-tool/issues/52#issuecomment-198737296

## 

## 

Jens Axel Søgaard

**Comment by k4b7** [comment]
> I notice the three lines:
> 
> npm WARN peerDependencies The peer dependency babel-core@^6.0.0 included
> from babel-loader will no
> npm WARN peerDependencies longer be automatically installed to fulfill the
> peerDependency
> npm WARN peerDependencies in npm 3+. Your application will need to depend
> on it explicitly.

Those warnings should affect anything.  Looking through the transcript, it looks like all of the dependencies have been installed including `babel-core`.  I thought that maybe I had some global module installed that was making a difference.  I had an old version of babel hanging around so I delete that but `npm start` still works.  I'm really stumped as to why this isn't working.

**Comment by soegaard** [comment]
Here is my transcript from running  npm start.

mbp:algebra-tool soegaard$ npm start

> mobile-keypad@0.0.1 start /Users/soegaard/Dropbox/GitHub/algebra-tool
> node server.js

Listening at localhost:3000
Hash: 6e7a82ffdff479d16eab
Version: webpack 1.12.14
Time: 7453ms
       Asset    Size  Chunks       Chunk Names
    index.js  253 kB       0       index
index.js.map  300 kB       0       index
chunk    {0} index.js, index.js.map (index) 214 kB [rendered]
    [0] multi index 52 bytes {0} [built] [1 error]
    [1](webpack)-dev-server/client?http://localhost:3000 2.67 kB {0}
[built]
    [2](webpack)/~/node-libs-browser/~/url/url.js 22.3 kB {0} [built]
    [3](webpack)/~/node-libs-browser/~/url/~/punycode/punycode.js 14.6 kB
{0} [built]
    [4](webpack)/buildin/module.js 251 bytes {0} [built]
    [5](webpack)/~/node-libs-browser/~/url/~/querystring/index.js 127
bytes {0} [built]
    [6](webpack)/~/node-libs-browser/~/url/~/querystring/decode.js 2.4 kB
{0} [built]
    [7](webpack)/~/node-libs-browser/~/url/~/querystring/encode.js 2.09 kB
{0} [built]
    [8](webpack)-dev-server/~/sockjs-client/lib/entry.js 244 bytes {0}
[built]
    [9](webpack)-dev-server/~/sockjs-client/lib/transport-list.js 613
bytes {0} [built]
   [10](webpack)-dev-server/~/sockjs-client/lib/transport/websocket.js
2.68 kB {0} [built]
   [11](webpack)/~/node-libs-browser/~/process/browser.js 2.06 kB {0}
[built]
   [12](webpack)-dev-server/~/sockjs-client/lib/utils/event.js 2 kB {0}
[built]
   [13](webpack)-dev-server/~/sockjs-client/lib/utils/random.js 746 bytes
{0} [built]
   [14](webpack)-dev-server/~/sockjs-client/lib/utils/browser-crypto.js
438 bytes {0} [built]
   [15](webpack)-dev-server/~/sockjs-client/lib/utils/url.js 975 bytes {0}
[built]
   [16](webpack)-dev-server/~/sockjs-client/~/url-parse/index.js 6.55 kB
{0} [built]
   [17](webpack)-dev-server/~/sockjs-client/~/url-parse/~/requires-port/index.js
753 bytes {0} [built]
   [18](webpack)-dev-server/~/sockjs-client/~/url-parse/lolcation.js 1.4
kB {0} [built]
   [19](webpack)-dev-server/~/sockjs-client/~/url-parse/~/querystringify/index.js
1.3 kB {0} [built]
   [20](webpack)-dev-server/~/sockjs-client/~/debug/browser.js 3.76 kB {0}
[built]
   [21](webpack)-dev-server/~/sockjs-client/~/debug/debug.js 4.1 kB {0}
[built]
   [22](webpack)-dev-server/~/sockjs-client/~/debug/~/ms/index.js 2.33 kB
{0} [built]
   [23](webpack)-dev-server/~/sockjs-client/~/inherits/inherits_browser.js
672 bytes {0} [built]
   [24](webpack)-dev-server/~/sockjs-client/lib/event/emitter.js 1.11 kB
{0} [built]
   [25](webpack)-dev-server/~/sockjs-client/lib/event/eventtarget.js 1.75
kB {0} [built]
   [26](webpack)-dev-server/~/sockjs-client/lib/transport/browser/websocket.js 58
bytes {0} [built]
   [27](webpack)-dev-server/~/sockjs-client/lib/transport/xhr-streaming.js
1.25 kB {0} [built]
   [28](webpack)-dev-server/~/sockjs-client/lib/transport/lib/ajax-based.js 1.31
kB {0} [built]
   [29](webpack)-dev-server/~/sockjs-client/lib/transport/lib/sender-receiver.js
1.15 kB {0} [built]
   [30](webpack)-dev-server/~/sockjs-client/lib/transport/lib/buffered-sender.js
2.3 kB {0} [built]
   [31](webpack)-dev-server/~/sockjs-client/lib/transport/lib/polling.js
1.32 kB {0} [built]
   [32](webpack)-dev-server/~/sockjs-client/lib/transport/receiver/xhr.js
1.58 kB {0} [built]
   [33](webpack)-dev-server/~/sockjs-client/lib/transport/sender/xhr-cors.js 343
bytes {0} [built]
   [34](webpack)-dev-server/~/sockjs-client/lib/transport/browser/abstract-xhr.js
4.67 kB {0} [built]
   [35](webpack)-dev-server/~/sockjs-client/lib/transport/sender/xhr-local.js 352
bytes {0} [built]
   [36](webpack)-dev-server/~/sockjs-client/lib/utils/browser.js 560 bytes
{0} [built]
   [37](webpack)-dev-server/~/sockjs-client/lib/transport/xdr-streaming.js
984 bytes {0} [built]
   [38](webpack)-dev-server/~/sockjs-client/lib/transport/sender/xdr.js
2.42 kB {0} [built]
   [39](webpack)-dev-server/~/sockjs-client/lib/transport/eventsource.js
766 bytes {0} [built]
   [40](webpack)-dev-server/~/sockjs-client/lib/transport/receiver/eventsource.js
1.58 kB {0} [built]
   [41](webpack)-dev-server/~/sockjs-client/lib/transport/browser/eventsource.js
37 bytes {0} [built]
   [42](webpack)-dev-server/~/sockjs-client/lib/transport/lib/iframe-wrap.js 981
bytes {0} [built]
   [43](webpack)-dev-server/~/sockjs-client/lib/transport/iframe.js 3.8 kB
{0} [built]
   [44](webpack)-dev-server/~/sockjs-client/~/json3/lib/json3.js 43.3 kB
{0} [built]
   [45](webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [46](webpack)-dev-server/~/sockjs-client/lib/version.js 25 bytes {0}
[built]
   [47](webpack)-dev-server/~/sockjs-client/lib/utils/iframe.js 4.95 kB
{0} [built]
   [48](webpack)-dev-server/~/sockjs-client/lib/utils/object.js 532 bytes
{0} [built]
   [49](webpack)-dev-server/~/sockjs-client/lib/transport/htmlfile.js 710
bytes {0} [built]
   [50](webpack)-dev-server/~/sockjs-client/lib/transport/receiver/htmlfile.js
2.17 kB {0} [built]
   [51](webpack)-dev-server/~/sockjs-client/lib/transport/xhr-polling.js
894 bytes {0} [built]
   [52](webpack)-dev-server/~/sockjs-client/lib/transport/xdr-polling.js
712 bytes {0} [built]
   [53](webpack)-dev-server/~/sockjs-client/lib/transport/jsonp-polling.js
1.02 kB {0} [built]
   [54](webpack)-dev-server/~/sockjs-client/lib/transport/receiver/jsonp.js 5.49
kB {0} [built]
   [55](webpack)-dev-server/~/sockjs-client/lib/transport/sender/jsonp.js
2.46 kB {0} [built]
   [56](webpack)-dev-server/~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [57](webpack)-dev-server/~/sockjs-client/lib/shims.js 18.2 kB {0}
[built]
   [58](webpack)-dev-server/~/sockjs-client/lib/utils/escape.js 2.31 kB
{0} [built]
   [59](webpack)-dev-server/~/sockjs-client/lib/utils/transport.js 1.35 kB
{0} [built]
   [60](webpack)-dev-server/~/sockjs-client/lib/utils/log.js 386 bytes {0}
[built]
   [61](webpack)-dev-server/~/sockjs-client/lib/event/event.js 485 bytes
{0} [built]
   [62](webpack)-dev-server/~/sockjs-client/lib/location.js 177 bytes {0}
[built]
   [63](webpack)-dev-server/~/sockjs-client/lib/event/close.js 295 bytes
{0} [built]
   [64](webpack)-dev-server/~/sockjs-client/lib/event/trans-message.js 292
bytes {0} [built]
   [65](webpack)-dev-server/~/sockjs-client/lib/info-receiver.js 2.22 kB
{0} [built]
   [66](webpack)-dev-server/~/sockjs-client/lib/transport/sender/xhr-fake.js 456
bytes {0} [built]
   [67](webpack)-dev-server/~/sockjs-client/lib/info-iframe.js 1.52 kB {0}
[built]
   [68](webpack)-dev-server/~/sockjs-client/lib/info-iframe-receiver.js
791 bytes {0} [built]
   [69](webpack)-dev-server/~/sockjs-client/lib/info-ajax.js 1.03 kB {0}
[built]
   [70](webpack)-dev-server/~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB
{0} [built]
   [71](webpack)-dev-server/~/sockjs-client/lib/facade.js 723 bytes {0}
[built]
   [72](webpack)-dev-server/~/strip-ansi/index.js 161 bytes {0} [built]
   [73](webpack)-dev-server/~/strip-ansi/~/ansi-regex/index.js 135 bytes
{0} [built]
   [74](webpack)/hot/only-dev-server.js 2.25 kB {0} [built]
   [75](webpack)/hot/log-apply-result.js 813 bytes {0} [built]

ERROR in ./src/index.js
Module build failed: Error: Couldn't find preset "stage-1" relative to
directory "/Users/soegaard/Dropbox/GitHub/algebra-tool"
    at
/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.addConfig
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File
(/Users/soegaard/Dropbox/GitHub/algebra-tool/node_modules/babel-core/lib/transformation/file/index.js:123:22)
 @ multi index
webpack: bundle is now VALID.

2016-03-19 19:43 GMT+01:00 Kevin Barabash notifications@github.com:

> I notice the three lines:
> 
> npm WARN peerDependencies The peer dependency babel-core@^6.0.0 included
> from babel-loader will no
> npm WARN peerDependencies longer be automatically installed to fulfill the
> peerDependency
> npm WARN peerDependencies in npm 3+. Your application will need to depend
> on it explicitly.
> 
> Those warnings should affect anything. Looking through the transcript, it
> looks like all of the dependencies have been installed including
> babel-core. I thought that maybe I had some global module installed that
> was making a difference. I had an old version of babel hanging around so I
> delete that but npm start still works. I'm really stumped as to why this
> isn't working.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Khan/algebra-tool/issues/52#issuecomment-198764907

## 

## 

Jens Axel Søgaard

**Comment by k4b7** [comment]
Trying running `npm install babel-preset-stage-1 --save-dev` and see if that helps.

**Comment by soegaard** [comment]
That did help. I can now run npm start and node api-server.js.

There is still something wrong in the browser though.
See http://imgur.com/2WlXRs9

2016-03-19 20:08 GMT+01:00 Kevin Barabash notifications@github.com:

> Trying running npm install babel-preset-stage-1 --save-dev and see if
> that helps.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Khan/algebra-tool/issues/52#issuecomment-198769810

## 

## 

Jens Axel Søgaard

**Comment by k4b7** [comment]
Awesome!  I'll add `babel-preset-stage-1` to package.json so that doesn't happen to anyone else.

> There is still something wrong in the browser though.

This is expected.  The 404 should be handled instead of dumping it to console.  The first time you go through a question, there are no hints so we don't show the 'take a hint' button.  To try out hints, you'll need to do two things:
- add `hints` to the URL param, e.g. `localhost:3000/?hints`
- going through the question at least once (this primes the hint server with at least one set of steps for a question).
