### ISSUE TITLE
save as MathML

### ISSUE THREAD

**Issue by buptkang** [kevinbarabash/mobile-keypad#54]
Hey there, 

Did the current library support the IO functionality to store the AST tree as the MathML?

Thanks

**Comment by k4b7** [comment]
No support for MathML... the AST is quite different from MathML, but writing a converter should be possible, although I would avoid MathML for web stuff b/c the support is not good, see http://caniuse.com/#feat=mathml.

**Comment by k4b7** [comment]
@buptkang what are you looking to do with the serialized version of the data structure?

**Comment by buptkang** [comment]
Indeed, my requirement is that users can input algebraic expression or equation as more comfortable as possible without any hint to derive that expression. Each expression should be treated as one step. Users can input several steps. I want to store and later render these stored steps to make further analysis. The data format should let me re-construct the AST. That is the reason I believe latex or asciimath format cannot support it? @kevinbarabash How do you think? Could you store the AST as a XML or whatever format instead?

**Comment by k4b7** [comment]
What kind of analysis do you want to do with the AST?  You could use `JSON.stringify` and `JSON.parse` on the AST itself.  I'm already doing this to send steps to the hint server, see app.js and api-server.js.

**Comment by buptkang** [comment]
Oh, I see, so you stored the AST as the json format. Okay, I will have a look first then. Thanks in advance.

**Comment by k4b7** [comment]
Sounds good.  The AST may change in the futures so if you need something stable you may want to use asciimath but then you'd have to convert back and forth.

**Comment by buptkang** [comment]
Thanks, yeah, I understand. I will play back and forth.
